# Those are the field names of the cargo tables of leaguepedia

# Tournament
tournaments_fields = {
    "Name",
    "DateStart",
    "Date",
    "Region",
    "League",
    "Rulebook",
    "TournamentLevel",
    "IsQualifier",
    "IsPlayoffs",
    "IsOfficial",
    "OverviewPage",
}

# Game
game_fields = {
    "GameId",
    "MatchId",
    "Tournament",
    "Team1",
    "Team2",
    "Winner",
    "Gamelength_Number",
    "DateTime_UTC",
    "Team1Score",
    "Team2Score",
    "Team1Bans",
    "Team2Bans",
    "Team1Picks",
    "Team2Picks",
    "Team1Players",
    "Team2Players",
    "Team1Dragons",
    "Team2Dragons",
    "Team1Barons",
    "Team2Barons",
    "Team1Towers",
    "Team2Towers",
    "Team1RiftHeralds",
    "Team2RiftHeralds",
    "Team1Inhibitors",
    "Team2Inhibitors",
    "Patch",
    "MatchHistory",
    "RiotPlatformGameId",
    "VOD",
    "Gamename",
    "N_GameInMatch",
    "OverviewPage",
}


# Game Player
game_players_fields = {
    "ScoreboardPlayers.Name=gameName",
    "ScoreboardPlayers.Role_Number=gameRoleNumber",
    "ScoreboardPlayers.Champion",
    "ScoreboardPlayers.Side",
    "Players.Name=irlName",
    "Players.Country",
    "Players.Birthdate",
    "Players.ID=currentGameName",
    # "Players.Image",
    # "Players.Team=currentTeam",
    # "Players.Role=currentRole",
    # "Players.SoloqueueIds",
}


# Ordered in the draft order for pro play as of June 2020
picks_bans_fields = [
    "Team1Ban1",
    "Team2Ban1",
    "Team1Ban2",
    "Team2Ban2",
    "Team1Ban3",
    "Team2Ban3",
    "Team1Pick1",
    "Team2Pick1",
    "Team2Pick2",
    "Team1Pick2",
    "Team1Pick3",
    "Team2Pick3",
    "Team2Ban4",
    "Team1Ban4",
    "Team2Ban5",
    "Team1Ban5",
    "Team2Pick4",
    "Team1Pick4",
    "Team1Pick5",
    "Team2Pick5",
]

# Tournament Rosters
tournament_rosters_fields = {
    "Team",
    "OverviewPage",
    "Region",
    "RosterLinks",
    "Roles",
    "Flags",
    "Footnotes",
    "IsUsed",
    "Tournament",
    "Short",
    "IsComplete",
    "PageAndTeam",
    "UniqueLine",
}

# Standings
standings_fields = {
    "OverviewPage",
    "Team",
    "PageAndTeam",
    "N",
    "Place",
    "WinSeries",
    "LossSeries",
    "TieSeries",
    "WinGames",
    "LossGames",
    "Points",
    "PointsTiebreaker",
    "Streak",
    "StreakDirection",
}

# Champions
champions_fields = {
    "Name",
    "Title",
    "ReleaseDate",
    "BE",
    "RP",
    "Attributes",
    "Resource",
    "RealName",
    "Health",
    "HPLevel",
    "HPRegen",
    "HPRegenLevel",
    "Mana",
    "ManaLevel",
    "ManaRegen",
    "ManaRegenLevel",
    "Energy",
    "EnergyRegen",
    "Movespeed",
    "AttackDamage",
    "ADLevel",
    "AttackSpeed",
    "ASLevel",
    "AttackRange",
    "Armor",
    "ArmorLevel",
    "MagicResist",
    "MagicResistLevel",
    "KeyInteger",
}

# Items
items_fields = {
    "Name",
    "Tier",
    "RiotId",
    "Recipe",
    "Cost",
    "TotalCost",
    "AD",
    "LifeSteal",
    "Health",
    "HPRegen",
    "Armor",
    "MR",
    "AttackDamage",
    "Crit",
    "AttackSpeed",
    "ArmorPen",
    "Lethality",
    "AttackRange",
    "Mana",
    "ManaRegen",
    "Energy",
    "EnergyRegen",
    "AP",
    "CDR",
    "AbilityHaste",
    "Omnivamp",
    "PhysVamp",
    "SpellVamp",
    "MPen",
    "MovespeedFlat",
    "MovespeedPercent",
    "Tenacity",
    "GoldGen",
    "OnHit",
    "BonusHP",
    "Healing",
    "HSPower",
    "SlowResist",
}

# Roster Changes
roster_changes_fields = {
    "Date_Sort",
    "Player",
    "Direction",
    "Team",
    "RolesIngame",
    "RolesStaff",
    "Roles",
    "RoleDisplay",
    "Role",
    "RoleModifier",
    "Status",
    "CurrentTeamPriority",
    "PlayerUnlinked",
    "AlreadyJoined",
    "Tournaments",
    "Source",
    "IsGCD",
    "Preload",
    "PreloadSortNumber",
    "Tags",
    "NewsId",
    "RosterChangeId",
    "N_LineInNews",
}

# Contracts
contracts_fields = {
    "Player",
    "Team",
    "ContractEnd",
    "ContractEndText",
    "IsRemoval",
    "NewsId",
}

# ScoreboardPlayers
scoreboard_players_fields = {
    "OverviewPage",
    "Name",
    "Link",
    "Champion",
    "Kills",
    "Deaths",
    "Assists",
    "SummonerSpells",
    "Gold",
    "CS",
    "DamageToChampions",
    "VisionScore",
    "Items",
    "Trinket",
    "KeystoneMastery",
    "KeystoneRune",
    "PrimaryTree",
    "SecondaryTree",
    "Runes",
    "TeamKills",
    "TeamGold",
    "Team",
    "TeamVs",
    "Time",
    "PlayerWin",
    "DateTime_UTC",
    "DST",
    "Tournament",
    "Role",
    "Role_Number",
    "IngameRole",
    "Side",
    "UniqueLine",
    "UniqueLineVs",
    "UniqueRole",
    "UniqueRoleVs",
    "GameId",
    "MatchId",
    "GameTeamId",
    "GameRoleId",
    "GameRoleIdVs",
    "StatsPage",
}
